#!/usr/bin/env python3
"""Embed wifi_station/web/* into web_assets.h (PROGMEM)."""

from pathlib import Path

Import("env")

WEB_DIR = Path(env.subst("$PROJECT_DIR")) / "web"
OUT = Path(env.subst("$PROJECT_DIR")) / "web_assets.h"
DELIM = "WSEMBED_7c4e9a"

FILES = [
    ("WEB_INDEX_HTML", "index.html"),
    ("WEB_STYLE_CSS", "style.css"),
    ("WEB_APP_JS", "app.js"),
    ("WEB_MESSAGE_HTML", "message.html"),
]


def main():
    parts = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by scripts/embed_web.py — edit web/* and rebuild.",
        "",
    ]
    for symbol, filename in FILES:
        data = (WEB_DIR / filename).read_text(encoding="utf-8")
        parts.append(f'static const char {symbol}[] PROGMEM = R"{DELIM}({data}){DELIM}";')
        parts.append(f"static const size_t {symbol}_LEN = sizeof({symbol}) - 1;")
        parts.append("")

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"embed_web: wrote {OUT}")


main()
