; Shared defaults included by wifi_station/ and wifi_solenoid/

[env]
platform = espressif32
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters =
	default
	esp32_exception_decoder
board = S3_V1_epaper
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-UARDUINO_USB_DFU_ON_BOOT
	-UARDUINO_USB_MSC_ON_BOOT
	-DCORE_DEBUG_LEVEL=0
	-DLILYGO_S3_E_PAPER_V_1_0
