; pio run -d wifi_solenoid

[platformio]
default_envs = wifi_solenoid
src_dir = .
boards_dir = ../boards
lib_dir = ../lib
extra_configs = ../platformio_common.ini

[env:wifi_solenoid]
extra_scripts = pre:scripts/embed_web.py
lib_deps =
	bblanchon/ArduinoJson@^7.1.0
	h2zero/NimBLE-Arduino@^2.1.0
