; pio run -d wifi_station

[platformio]
default_envs = wifi_station
src_dir = .
boards_dir = ../boards
lib_dir = ../lib
extra_configs = ../platformio_common.ini

[env:wifi_station]
extra_scripts = pre:scripts/embed_web.py
lib_deps =
	bblanchon/ArduinoJson@^7.1.0
	https://github.com/infinite-tree/Influx-Arduino
