#pragma once
#include <Arduino.h>

// Auto-generated by scripts/embed_web.py — edit web/* and rebuild.

static const char WEB_INDEX_HTML[] PROGMEM = R"WSEMBED_7c4e9a(<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>Station</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <div class="app" id="app">
    <h1 class="hdr">Station</h1>

    <section class="panel panel-now">
      <div class="lbl">Now</div>
      <div class="now-main" id="now-main">Loading…</div>
      <div class="now-sub" id="now-sub"></div>
      <div class="alert hidden" id="solenoid-alert">Could not reach solenoid controller</div>
      <div class="alert hidden" id="vfd-alert">VFD drive fault — check Frenic Mini</div>
      <div class="chips" id="chips"></div>
    </section>

    <section class="panel">
      <div class="lbl panel-lbl">Last watering</div>
      <table class="zone-table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">When</th>
            <th scope="col">Duration</th>
          </tr>
        </thead>
        <tbody id="last-table"></tbody>
      </table>
    </section>

    <section class="panel ctrl" id="controls"></section>
  </div>
  <script src="/app.js"></script>
</body>
</html>
)WSEMBED_7c4e9a";
static const size_t WEB_INDEX_HTML_LEN = sizeof(WEB_INDEX_HTML) - 1;

static const char WEB_STYLE_CSS[] PROGMEM = R"WSEMBED_7c4e9a(*{box-sizing:border-box}
html,body{height:100%;margin:0}
body{font-family:system-ui,-apple-system,sans-serif;font-size:15px;line-height:1.35;color:#1a1a1a;background:#e8ecf1;-webkit-text-size-adjust:100%}
.app{height:100dvh;max-width:26rem;margin:0 auto;padding:8px 10px;padding:max(8px,env(safe-area-inset-top)) max(10px,env(safe-area-inset-right)) max(8px,env(safe-area-inset-bottom)) max(10px,env(safe-area-inset-left));display:flex;flex-direction:column;gap:8px;overflow:hidden}
.hidden{display:none!important}
.hdr{font-size:1.15rem;font-weight:700;color:#0056b3;text-align:center;margin:0}
.panel{background:#fff;border-radius:10px;padding:10px 12px;box-shadow:0 1px 3px rgba(0,0,0,.07)}
.panel-now{background:linear-gradient(145deg,#0056b3,#0074c2);color:#fff}
.lbl{opacity:.85;font-size:.7rem;font-weight:600;text-transform:uppercase;letter-spacing:.04em}
.panel-lbl{color:#666;margin-bottom:6px}
.panel-now .lbl{color:rgba(255,255,255,.9)}
.now-main{font-size:1.2rem;font-weight:700;margin:2px 0;font-variant-numeric:tabular-nums}
.now-sub{font-size:.82rem;opacity:.92}
.alert{background:#f8d7da;color:#721c24;border-radius:8px;padding:8px 10px;font-size:.82rem;font-weight:600;margin-top:6px}
.chips{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:8px}
.chip{border-radius:8px;padding:6px 2px;text-align:center;font-size:.68rem;font-weight:700;line-height:1.15}
.chip b{display:block;font-size:.62rem;font-weight:600;opacity:.85;margin-bottom:2px}
.chip-off{background:rgba(0,0,0,.15);color:rgba(255,255,255,.75)}
.chip-on{background:rgba(255,255,255,.95);color:#155724}
.chip-err{background:#ffc9c9;color:#721c24}
.zone-table{width:100%;border-collapse:collapse;font-size:.8rem}
.zone-table thead th{font-size:.65rem;font-weight:600;text-transform:uppercase;letter-spacing:.04em;color:#888;padding:0 4px 6px;text-align:left}
.zone-table thead th:nth-child(n+2){text-align:right}
.zone-table tbody th{font-weight:600;color:#444;text-align:left;padding:7px 4px;border-top:1px solid #eee}
.zone-table tbody td{padding:7px 4px;border-top:1px solid #eee;text-align:right;font-weight:600;color:#0056b3;font-variant-numeric:tabular-nums}
.zone-table tbody td.muted{color:#888;font-weight:500}
.ctrl form{display:flex;flex-direction:column;gap:6px}
.ctrl-row{display:flex;gap:6px}
.ctrl-row input,.ctrl-row select{flex:1;min-width:0;min-height:42px;padding:8px 10px;font-size:16px;border:1px solid #ccc;border-radius:8px;background:#fff}
.btn{width:100%;min-height:44px;border:none;border-radius:9px;font-size:1rem;font-weight:700;color:#fff;background:#0056b3;cursor:pointer;-webkit-appearance:none}
.btn-stop{background:#b02a37}
)WSEMBED_7c4e9a";
static const size_t WEB_STYLE_CSS_LEN = sizeof(WEB_STYLE_CSS) - 1;

static const char WEB_APP_JS[] PROGMEM = R"WSEMBED_7c4e9a((function () {
  const POLL_MS = 3000;

  const ZONE_ROWS = [
    ['Zone 1', 'z1'],
    ['Zone 2', 'z2'],
    ['Greenhouse', 'gh'],
    ['Water cannon', 'wc']
  ];

  function chipHtml(label, status) {
    const cls = status === 'on' ? 'chip-on' : status === 'error' ? 'chip-err' : 'chip-off';
    const word = status === 'on' ? 'On' : status === 'error' ? 'Error' : 'Off';
    return '<div class="chip ' + cls + '"><b>' + label + '</b>' + word + '</div>';
  }

  function renderControls(running) {
    const el = document.getElementById('controls');
    if (running) {
      el.innerHTML =
        '<form action="/stop" method="post">' +
        '<input class="btn btn-stop" type="submit" value="Stop watering">' +
        '</form>';
      return;
    }
    el.innerHTML =
      '<form action="/start" method="post">' +
      '<div class="ctrl-row">' +
      '<input type="number" name="duration" min="1" value="10" inputmode="numeric" aria-label="Minutes">' +
      '<select name="zone" aria-label="What to water">' +
      '<option value="1">Zone 1</option>' +
      '<option value="2">Zone 2</option>' +
      '<option value="3">Greenhouse</option>' +
      '<option value="4">Zones 1+2</option>' +
      '<option value="5">Water cannon</option>' +
      '</select></div>' +
      '<input class="btn" type="submit" value="Start watering">' +
      '</form>';
  }

  function renderLastTable(history) {
    const h = history || {};
    let html = '';
    for (let i = 0; i < ZONE_ROWS.length; i++) {
      const label = ZONE_ROWS[i][0];
      const key = ZONE_ROWS[i][1];
      const row = h[key] || { when: 'Never', duration: '—' };
      const muted = row.when === 'Never';
      html +=
        '<tr><th scope="row">' + label + '</th>' +
        '<td' + (muted ? ' class="muted"' : '') + '>' + row.when + '</td>' +
        '<td' + (muted ? ' class="muted"' : '') + '>' + row.duration + '</td></tr>';
    }
    document.getElementById('last-table').innerHTML = html;
  }

  function renderStatus(s) {
    document.getElementById('now-main').textContent = s.now_main || '—';
    document.getElementById('now-sub').textContent = s.now_sub || '';

    const solenoidAlert = document.getElementById('solenoid-alert');
    if (s.solenoid_error) {
      solenoidAlert.classList.remove('hidden');
    } else {
      solenoidAlert.classList.add('hidden');
    }

    const vfdAlert = document.getElementById('vfd-alert');
    if (s.vfd_error) {
      vfdAlert.classList.remove('hidden');
    } else {
      vfdAlert.classList.add('hidden');
    }

    const z = s.zones || {};
    document.getElementById('chips').innerHTML =
      chipHtml('Z1', z.z1) +
      chipHtml('Z2', z.z2) +
      chipHtml('GH', z.gh) +
      chipHtml('WC', z.wc);

    renderLastTable(s.last_watering);
    renderControls(!!s.timer_running);
  }

  function refresh() {
    fetch('/status')
      .then(function (r) { return r.json(); })
      .then(renderStatus)
      .catch(function () {
        document.getElementById('now-main').textContent = 'Offline';
      });
  }

  refresh();
  setInterval(refresh, POLL_MS);
})();
)WSEMBED_7c4e9a";
static const size_t WEB_APP_JS_LEN = sizeof(WEB_APP_JS) - 1;

static const char WEB_MESSAGE_HTML[] PROGMEM = R"WSEMBED_7c4e9a(<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="refresh" content="2;url=/">
  <title>Station</title>
  <style>
    body{font-family:system-ui,sans-serif;margin:0;padding:24px;text-align:center;background:#e8ecf1}
    h2{color:#0056b3;margin:0 0 8px}
    p{color:#444;margin:0}
  </style>
</head>
<body>
  <h2 id="msg">Done</h2>
  <p>Returning home…</p>
  <script>
    var p = new URLSearchParams(location.search);
    if (p.get('m')) document.getElementById('msg').textContent = p.get('m');
  </script>
</body>
</html>
)WSEMBED_7c4e9a";
static const size_t WEB_MESSAGE_HTML_LEN = sizeof(WEB_MESSAGE_HTML) - 1;

